events {}
http {
  upstream python { server python:5000; }
  upstream node { server node:3000; }
  upstream spring { server spring:8080; }
  upstream php { server php:80; }

  server {
    listen 80;

    location /python/ { proxy_pass http://python/; }
    location /node/ { proxy_pass http://node/; }
    location /spring/ { proxy_pass http://spring/; }
    location /php/ { proxy_pass http://php/; }
  }
}